//
// Created by Orion Letizi on 11/15/23.
//

#ifndef OL_DSP_CC_MAP_H
#define OL_DSP_CC_MAP_H

#define CC_VOLUME 7

#define CC_REVERB_TIME 32
#define CC_REVERB_CUTOFF 33
#define CC_REVERB_BALANCE 34

#define CC_DELAY_TIME 35
#define CC_DELAY_FEEDBACK 36
#define CC_DELAY_CUTOFF 37
#define CC_DELAY_RESONANCE 38
#define CC_DELAY_BALANCE 39
#define CC_DELAY_FILTER_TYPE 40

#define CC_LPF_CUTOFF 41
#define CC_LPF_RESONANCE 42
#define CC_LPF_TYPE 43
#define CC_LPF_DRIVE 44
#define CC_LPF_ENV_AMT 45

#define CC_LPF_ENV_DELAY 46
#define CC_LPF_ENV_ATTACK 47
#define CC_LPF_ENV_HOLD 48
#define CC_LPF_ENV_DECAY 49
#define CC_LPF_ENV_SUSTAIN 50
#define CC_LPF_ENV_RELEASE 51

#endif //OL_DSP_CC_MAP_H
